'use client';
import {useEffect,useRef,useState} from 'react';
import {PROFILE} from '@/lib/data';
import {scrollToTarget} from '@/lib/scroll';
export default function Hero(){const video=useRef<HTMLVideoElement>(null);const root=useRef<HTMLElement>(null);const visible=useRef(true);const manuallyMuted=useRef(false);const [sound,setSound]=useState(false);const [blocked,setBlocked]=useState(true);
useEffect(()=>{const v=video.current;if(!v)return;const play=async()=>{if(!visible.current)return;v.muted=false;try{await v.play();setSound(true);setBlocked(false);}catch{v.muted=true;setSound(false);v.play().catch(()=>{});}};const unlock=(e:Event)=>{if(e.target instanceof Element&&e.target.closest(".sound"))return;if(visible.current&&!manuallyMuted.current)void play();};const events=['pointerdown','keydown','touchend'] as const;events.forEach(e=>window.addEventListener(e,unlock,{once:true}));void play();const o=new IntersectionObserver(([e])=>{visible.current=e.intersectionRatio>=.35;if(visible.current){v.muted=manuallyMuted.current||v.muted;v.play().catch(()=>{});}else v.pause();},{threshold:[0,.35,1]});if(root.current)o.observe(root.current);return()=>{o.disconnect();events.forEach(e=>window.removeEventListener(e,unlock));v.pause();};},[]);
const toggle=async()=>{const v=video.current;if(!v)return;const next=v.muted;manuallyMuted.current=!next;v.muted=!next;setSound(next);setBlocked(false);if(visible.current)await v.play().catch(()=>setBlocked(true));};
return <section ref={root} className="hero" id="top" aria-label="Introduction"><div className="hero-word" aria-hidden="true">{PROFILE.firstName}</div><div className="hero-caption"><span className="mono">{PROFILE.location}</span><span className="mono">{PROFILE.name}</span></div><div className="hero-video"><video ref={video} autoPlay muted loop playsInline preload="auto" poster="/portrait-bust.webp" aria-label={`${PROFILE.name} speaking a self-introduction`}><source src="/hero/hero.webm" type="video/webm"/><source src="/hero/hero.mp4" type="video/mp4"/></video></div><div className="hero-copy"><p className="mono">React.js · Node.js · Django</p><h1>Web <em>Developer.</em></h1><div className="hero-bottom"><p>Responsive and scalable<br/>web applications.</p><div className="hero-actions"><a className="pill primary" href="#work" onClick={e=>{e.preventDefault();scrollToTarget('work');}}>Explore work <span>↗</span></a><a className="pill" href="#contact" onClick={e=>{e.preventDefault();scrollToTarget('contact');}}>Let’s talk</a><a className="resume-link" href={PROFILE.resume} download>Résumé ↓</a></div><button className={`sound ${blocked?'ping':''}`} aria-label={sound?'Mute introduction':'Play introduction with sound'} onClick={toggle}>{sound?'❚❚':'▶'}</button></div></div><style>{`
.hero{background:var(--paper);position:relative;min-height:min(100svh,1040px);padding:130px var(--gutter) 45px;max-width:1920px;margin:auto;isolation:isolate;overflow:hidden}.hero-word{position:absolute;top:19%;left:50%;transform:translateX(-50%);font-size:clamp(100px,17.8vw,340px);font-weight:750;letter-spacing:-.065em;text-transform:uppercase;color:transparent;-webkit-text-stroke:1px #0d0d0d27;white-space:nowrap;z-index:-2}.hero-caption{display:flex;justify-content:space-between;max-width:1320px;margin:auto}.hero-video{position:relative;z-index:-1;mix-blend-mode:multiply;height:min(70svh,800px);width:100%;display:flex;justify-content:center;margin-top:-35px;pointer-events:none}.hero-video video{height:100%;max-width:100%;aspect-ratio:768/960;object-fit:contain;mix-blend-mode:multiply}.hero-copy{max-width:1320px;margin:-125px auto 0;position:relative}.hero-copy>p{margin-bottom:15px}.hero h1{font-size:clamp(68px,9.1vw,160px);line-height:.95;letter-spacing:-.065em;font-weight:650;white-space:nowrap;margin-bottom:34px}.hero h1 em{font-weight:400}.hero-bottom{display:flex;align-items:center;justify-content:space-between;gap:20px}.hero-bottom>p{font-size:16px;color:var(--ink-2);line-height:1.4}.hero-actions{display:flex;align-items:center;gap:12px}.resume-link{font-size:14px;border-bottom:1px solid var(--ink);margin-left:12px;padding:5px 0}.sound{width:46px;height:46px;border-radius:50%;background:var(--ink);color:white;position:relative;flex-shrink:0}.ping:after{content:'';position:absolute;inset:-6px;border:1px solid #0d0d0d50;border-radius:50%;animation:ping 2s infinite}@keyframes ping{to{transform:scale(1.3);opacity:0}}@media(min-width:1600px){.hero-copy{margin-top:-150px}}@media(max-width:700px){.hero{min-height:95svh;padding-top:110px;padding-bottom:35px}.hero-caption{font-size:10px}.hero-caption span:last-child{display:none}.hero-word{top:24%;font-size:21vw}.hero-video{height:62svh;margin-top:-25px}.hero-copy{margin-top:-65px}.hero h1{white-space:normal;font-size:clamp(62px,13vw,90px);margin-bottom:24px}.hero-copy>p{font-size:10px}.hero-bottom{flex-wrap:wrap;gap:20px}.hero-bottom>p{font-size:14px}.hero-actions{order:3;width:100%;gap:8px}.hero-actions .pill{padding:13px 18px;font-size:13px}.resume-link{margin-left:auto;font-size:12px}.hero h1 em{display:block}}
`}</style></section>;}
