'use client';
import {useEffect,useRef,useState} from 'react';
import {NAV,PROFILE} from '@/lib/data';
import {useScrollProgress} from '@/lib/hooks';
import {scrollToTarget} from '@/lib/scroll';
export default function Navigation(){const progress=useScrollProgress();const [active,setActive]=useState('');const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);const menuRef=useRef<HTMLDivElement>(null);const toggle=useRef<HTMLButtonElement>(null);
useEffect(()=>{const onScroll=()=>setScrolled(scrollY>40);window.addEventListener('scroll',onScroll,{passive:true});const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);}),{rootMargin:'-45% 0px -50% 0px'});NAV.forEach(n=>{const el=document.getElementById(n.id);if(el)o.observe(el);});return()=>{o.disconnect();window.removeEventListener('scroll',onScroll);};},[]);
useEffect(()=>{if(!open)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';const controls=menuRef.current?.querySelectorAll<HTMLAnchorElement|HTMLButtonElement>('a,button');controls?.[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}if(e.key==='Tab'&&controls?.length){const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=prev;document.removeEventListener('keydown',key);};},[open]);
const link=(e:React.MouseEvent,id:string)=>{e.preventDefault();setOpen(false);requestAnimationFrame(()=>scrollToTarget(id));};
return <><div className="top-progress" style={{transform:`scaleX(${progress})`}}/><header className={`navigation ${scrolled?'scrolled':''}`}><a href="#top" className="identity" aria-label={`${PROFILE.name}, back to top`} onClick={e=>link(e,'top')}><span className="initials" aria-hidden="true">{PROFILE.initials}</span><span className="nav-name">{PROFILE.name}</span></a><nav className="desktop-nav" aria-label="Main navigation"><span className="nav-track" style={{opacity:active?1:0,transform:`translateX(${Math.max(0,NAV.findIndex(n=>n.id===active))*100}%)`}}/>{NAV.map(n=><a key={n.id} href={`#${n.id}`} className={active===n.id?'active':''} aria-current={active===n.id?'location':undefined} onClick={e=>link(e,n.id)}>{n.label}</a>)}</nav><button ref={toggle} className="menu-toggle pill" onClick={()=>setOpen(true)} aria-expanded={open} aria-controls="mobile-menu">Menu <span>＋</span></button></header>{open&&<div ref={menuRef} className="mobile-overlay" id="mobile-menu" role="dialog" aria-modal="true" aria-label="Navigation"><button className="pill close-menu" onClick={()=>{setOpen(false);toggle.current?.focus();}}>Close ×</button><nav aria-label="Mobile navigation">{NAV.map((n,i)=><a key={n.id} href={`#${n.id}`} style={{'--i':i} as React.CSSProperties} onClick={e=>link(e,n.id)}><small>0{i+1}</small>{n.label}</a>)}</nav><p>{PROFILE.email}</p></div>}<style>{`
.navigation{position:fixed;z-index:50;top:24px;left:var(--gutter);right:var(--gutter);display:flex;align-items:center;justify-content:space-between;gap:20px}.identity{display:flex;align-items:center;gap:12px;font-size:14px;font-weight:650}.initials{display:grid;place-items:center;width:44px;height:44px;border:1px solid var(--ink);border-radius:50%;transition:transform .8s var(--ease),background .4s,color .4s}.identity:hover .initials{transform:rotate(360deg)}.nav-name{transition:opacity .3s}.scrolled .nav-name{opacity:0}.scrolled .initials{background:var(--ink);color:var(--paper)}.desktop-nav{display:flex;position:relative;border:1px solid var(--line);padding:6px;border-radius:100px;background:#f4f2eecf;backdrop-filter:blur(12px)}.scrolled .desktop-nav{background:#ffffffb8;box-shadow:0 8px 30px #00000006}.desktop-nav a{position:relative;width:100px;padding:12px 0;text-align:center;font-size:14px;transition:color .3s}.desktop-nav a.active{color:white}.nav-track{position:absolute;top:6px;bottom:6px;left:6px;width:100px;border-radius:50px;background:var(--ink);transition:transform .5s var(--ease),opacity .3s}.top-progress{position:fixed;top:0;left:0;right:0;height:2px;background:var(--ink);transform-origin:left;z-index:90}.menu-toggle{display:none}.mobile-overlay{position:fixed;inset:0;z-index:80;background:var(--paper);padding:32px var(--gutter);animation:menu-reveal .5s var(--ease)}.close-menu{margin-left:auto;display:block}.mobile-overlay nav{display:flex;flex-direction:column;margin-top:8vh}.mobile-overlay nav a{display:flex;align-items:center;gap:25px;font-size:clamp(34px,8vw,64px);padding:10px 0;animation:mobile-link .5s var(--ease) both;animation-delay:calc(var(--i)*60ms)}.mobile-overlay small{font:12px var(--font-mono);color:var(--mute)}.mobile-overlay p{margin-top:30px;font-size:14px}.menu-toggle span{margin-left:15px}@keyframes menu-reveal{from{clip-path:inset(0 0 100%)}to{clip-path:inset(0)}}@keyframes mobile-link{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:none}}@media(max-width:850px){.navigation{top:18px}.desktop-nav{display:none}.menu-toggle{display:block;background:#ffffffc0;backdrop-filter:blur(12px)}.nav-name{font-size:12px}}
`}</style></>;}
